# Exported from Render on 2025-03-18T14:22:33Z
services:
- type: web
  name: Bandstream-AiAgent
  runtime: docker
  repo: https://github.com/DenisAIagent/Bandstream-AiAgent
  plan: free
  envVars:
  - key: GOOGLE_OAUTH_CLIENT_SECRET
    sync: false
  - key: DEEZER_ACCESS_TOKEN
    sync: false
  - key: SPOTIFY_CLIENT_SECRET
    sync: false
  - key: SPOTIFY_CLIENT_ID
    sync: false
  - key: SERPAPI_KEY
    sync: false
  region: oregon
  healthCheckPath: /health
  dockerContext: ./api_server
  dockerfilePath: ./api_server/Dockerfile
  previews:
    generation: manual
version: "1"
